[versions]
activity-compose = "1.8.2"
andserver = "2.1.12"
coil-compose-version = "2.0.0-rc03"
core-ktx = "1.8.0"
google-gson = "2.9.1"
junit = "4.13.2"
kotlinx-coroutines-android = "1.6.2"
lifecycle = "2.7.0"
okhttp = "4.10.0"
ktor-version = "2.0.3"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
accompanist-version = "0.24.13-rc"
savedstate = "1.2.1"
mlkit-text = "16.0.0-beta5"

[libraries]
# androidx
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
androidx-activity-ktx = "androidx.activity:activity-ktx:1.9.0"
androidx-webkit = "androidx.webkit:webkit:1.10.0"
documentfile = "androidx.documentfile:documentfile:1.0.1"
androidx-savedstate = { module = "androidx.savedstate:savedstate", version.ref = "savedstate" }
androidx-savedstate-ktx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "savedstate" }
preference-ktx = "androidx.preference:preference-ktx:1.2.1"
androidx-annotation = "androidx.annotation:annotation:1.7.1"
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
# material ======================================
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-material3 = "androidx.compose.material3:material3:1.2.1"
compose-material3-window-size = "androidx.compose.material3:material3-window-size-class:1.2.1"
compose-material3-adaptive-navigation-suite = "androidx.compose.material3:material3-adaptive-navigation-suite:1.0.0-alpha06"

#lifecycle
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }

# androidx compose
compose-bom = "androidx.compose:compose-bom:2024.04.01"
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material = { module = "androidx.compose.material:material" }
compose-ui = { module = "androidx.compose.ui:ui" }

compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-animation-core = { module = "androidx.compose.animation:animation-core" }
compose-animation = { module = "androidx.compose.animation:animation" }
# accompanist
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist-version" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-version" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist-version" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist-version" }
accompanist-appcompat-theme = { module = "com.google.accompanist:accompanist-appcompat-theme", version.ref = "accompanist-version" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist-version" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-version" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist-version" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-version" }
##########################
commons-exec = "org.apache.commons:commons-exec:1.3"
commons-io = "commons-io:commons-io:2.6"
eventbus = "org.greenrobot:eventbus:3.3.1"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
# ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor-version" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor-version" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
# mlkit
mlkit-text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "mlkit-text" }
mlkit-text-recognition-chinese = { module = "com.google.mlkit:text-recognition-chinese", version.ref = "mlkit-text" }
mlkit-text-recognition-devanagari = { module = "com.google.mlkit:text-recognition-devanagari", version.ref = "mlkit-text" }
mlkit-text-recognition-japanese = { module = "com.google.mlkit:text-recognition-japanese", version.ref = "mlkit-text" }
mlkit-text-recognition-korean = { module = "com.google.mlkit:text-recognition-korean", version.ref = "mlkit-text" }
#rxjava
rxjava2 = "io.reactivex.rxjava2:rxjava:2.2.21"
rxjava2-rxandroid = "io.reactivex.rxjava2:rxandroid:2.1.1"
rxjava3 = "io.reactivex.rxjava3:rxjava:3.1.5"
rxjava3-rxandroid = "io.reactivex.rxjava3:rxandroid:3.0.2"
javet-android-node = "com.caoccao.javet:javet-android-node:3.1.4"

#test libraries ===================================
junit = { module = "junit:junit", version.ref = "junit" }
#leakcanary
leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.13"
leakcanary-object-watcher-android = "com.squareup.leakcanary:leakcanary-object-watcher-android:2.13"
test-runner = "androidx.test:runner:1.5.2"
test-rules = "androidx.test:rules:1.5.0"
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

timscriptov-apksigner ="com.github.TimScriptov:apksigner:1.2.0"
andserver-processor = { module = "com.yanzhenjie.andserver:processor", version.ref = "andserver" }
andserver-api = { module = "com.yanzhenjie.andserver:api", version.ref = "andserver" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose-version" }
#Deprecated ========================================
#Glide
glide = "com.github.bumptech.glide:glide:4.8.0"
glide-ksp = "com.github.bumptech.glide:ksp:4.14.2"
glide-compiler = "com.github.bumptech.glide:compiler:4.12.0"
[plugins]

[bundles]
ktor = ["ktor-server-core", "ktor-server-netty", "ktor-server-websockets", "ktor-client-websockets", "ktor-client-okhttp", "ktor-client-core"]
accompanist = ["accompanist-webview", "accompanist-systemuicontroller", "accompanist-insets-ui", "accompanist-insets", "accompanist-appcompat-theme", "accompanist-swiperefresh", "accompanist-pager", "accompanist-pager-indicators", "accompanist-permissions"]
mlkit = [
    "mlkit-text-recognition",
    "mlkit-text-recognition-chinese",
    "mlkit-text-recognition-devanagari",
    "mlkit-text-recognition-japanese",
    "mlkit-text-recognition-korean"
]