[versions]
activity-compose = "1.3.1"
compose-version = "1.2.0-rc01"
andserver = "2.1.12"
core-ktx = "1.8.0"
google-gson = "2.9.1"
junit = "4.13.2"
kotlinx-coroutines-android = "1.6.2"
okhttp = "4.10.0"
ktor-version = "2.0.3"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.4.2"
material = "1.9.0"
accompanist-version = "0.24.13-rc"
text-recognition = "16.0.0-beta6"
text-recognition-chinese = "16.0.0"

[libraries]

androidx-annotation = "androidx.annotation:annotation:1.4.0"
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
# androidx compose
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-version" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-version" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-version" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-version" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-version" }
#compose-bom = "androidx.compose:compose-bom:2023.03.00"
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-version" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose-version" }
compose-animation-core = { module = "androidx.compose.animation:animation-core", version.ref = "compose-version" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose-version" }
# accompanist
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist-version" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-version" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist-version" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist-version" }
accompanist-appcompat-theme = { module = "com.google.accompanist:accompanist-appcompat-theme", version.ref = "accompanist-version" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist-version" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-version" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist-version" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-version" }
##########################
androidx-activity-ktx = "androidx.activity:activity-ktx:1.5.1"

commons-io = "commons-io:commons-io:2.6"
eventbus = "org.greenrobot:eventbus:3.3.1"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
nanohttpd-webserver = "org.nanohttpd:nanohttpd-webserver:2.3.1"
androidx-webkit = "androidx.webkit:webkit:1.7.0"
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
documentfile = "androidx.documentfile:documentfile:1.0.1"
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
junit = { module = "junit:junit", version.ref = "junit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
# ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor-version" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor-version" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
#rxjava
rxjava2 = "io.reactivex.rxjava2:rxjava:2.2.21"
rxjava2-rxandroid = "io.reactivex.rxjava2:rxandroid:2.1.1"
rxjava3 = "io.reactivex.rxjava3:rxjava:3.1.5"
rxjava3-rxandroid = "io.reactivex.rxjava3:rxandroid:3.0.2"
#leakcanary
leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.12"
leakcanary-object-watcher-android = "com.squareup.leakcanary:leakcanary-object-watcher-android:2.12"

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
andserver-processor = { module = "com.yanzhenjie.andserver:processor", version.ref = "andserver" }
andserver-api = { module = "com.yanzhenjie.andserver:api", version.ref = "andserver" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "text-recognition" }
text-recognition-chinese = { module = "com.google.mlkit:text-recognition-chinese", version.ref = "text-recognition-chinese" }
text-recognition-korean = { module = "com.google.mlkit:text-recognition-korean", version.ref = "text-recognition" }
text-recognition-japanese = { module = "com.google.mlkit:text-recognition-japanese", version.ref = "text-recognition" }
text-recognition-devanagari = { module = "com.google.mlkit:text-recognition-devanagari", version.ref = "text-recognition" }
[plugins]

[bundles]
ktor = ["ktor-server-core", "ktor-server-netty", "ktor-server-websockets", "ktor-client-websockets", "ktor-client-okhttp", "ktor-client-core"]
accompanist = ["accompanist-webview", "accompanist-systemuicontroller", "accompanist-insets-ui", "accompanist-insets", "accompanist-appcompat-theme", "accompanist-swiperefresh", "accompanist-pager", "accompanist-pager-indicators", "accompanist-permissions"]