[versions]
androidGradlePlugin = "8.4.2"
androidTools = "31.5.2"
androidIssueReporterVersion = "1.3.1"
androidxCollection = "1.4.3"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.25"
android-job-version = "1.4.3"
androidxWebkit = "1.11.0"
androidxPreference = "1.2.1"
androidxActivity = "1.9.1"
androidxAnnotation = "1.8.2"
androidxDocumentfile = "1.0.1"
android-plugin-client-sdk-for-locale-version = "4.0.3"
activity-compose = "1.9.1"
analytics-version = "14.4.0"
android-joda-version = "2.12.7"
android-multi-level-listview-version = "1.1"
androidLoggingLog4jVersion = "1.0.3"
andserver = "2.1.12"
bcpkix-jdk15on-version = "1.58.0.0"
bignerdranch-expandablerecyclerview = "3.0.0-RC1"
cardview-version = "1.0.0"
coil = "2.7.0"
commons-lang3-version = "3.15.0"
commonmark-java-version = "commonmark-parent-0.22.0"
commons-version = "0.9.6.0"
glide = "4.16.0"
core = "4.6.2"
core-ktx = "1.13.1"
core-version = "0.9.2.3"
crashreport-version = "4.0.0"
enhancedfloaty-version = "0.31"
expandablerecyclerview-version = "1.3"
google-gson = "2.11.0"
groovy-json-version = "3.0.22"
junit = "4.13.2"
keeplive-version = "1.1.22"
kotlinx-coroutines-android = "1.8.1"
kotlinx-serialization = "1.7.1"
licensesdialog-version = "2.2.0"
androidxLifecycle = "2.8.4"
localbroadcastmanager-version = "1.1.0"
leakcanary = "2.14"
log4jVersion = "1.2.17"
slf4jVersion = "2.0.16"
logbackAndroidVersion = "3.0.0"
multidex-version = "2.0.1"
mutabletheme-version = "1.0.0"
okhttp = "4.12.0"
ktor = "2.3.12"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
accompanist-version = "0.35.2-beta"
org-eclipse-paho-android-service-version = "1.1.1"
org-eclipse-paho-client-mqttv3-version = "1.2.5"
plugin-version = "2.1.12"
quickie-bundled-version = "1.5.0"
recyclerview-flexibledivider-version = "1.4.0"
rootshell-version = "1.6"
roundedimageview-version = "2.3.0"
savedstate = "1.2.1"
androidxComposeBom = "2024.06.00"
settingscompat-version = "1.1.5"
speed-dial-compose-version = "1.0.0-alpha03"
swiperefreshlayout-version = "1.1.0"
tbssdk-version = "44286"
tesseract4android-version = "4.1.1"
mlkitTextRecognition = "16.0.1"
utils-everywhere-version = "3.1.1"
viewpager2-version = "1.1.0"
websocket2-version = "2.1.4"
work-runtime-version = "2.9.1"
zip4j-version = "1.3.2"
rxjava2 = "2.2.21"
rxandroid2 = "2.1.1"
eventbus = "3.3.1"
commons-io = "2.16.1"
[libraries]
# androidx
analytics = { module = "com.flurry.android:analytics", version.ref = "analytics-version" }
android-expandablerecyclerview = { module = "com.bignerdranch.android:expandablerecyclerview", version.ref = "bignerdranch-expandablerecyclerview" }
android-issue-reporter = { module = "com.heinrichreimersoftware:android-issue-reporter", version.ref = "androidIssueReporterVersion" }
android-job = { module = "com.evernote:android-job", version.ref = "android-job-version" }
android-joda = { module = "net.danlew:android.joda", version.ref = "android-joda-version" }
android-logging-log4j = { module = "de.mindpipe.android:android-logging-log4j", version.ref = "androidLoggingLog4jVersion" }

android-plugin-client-sdk-for-locale = { module = "com.twofortyfouram:android-plugin-client-sdk-for-locale", version.ref = "android-plugin-client-sdk-for-locale-version" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview-version" }

androidx-collection = { module = "androidx.collection:collection", version.ref = "androidxCollection" }
androidx-localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager-version" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex-version" }
androidx-savedstate = { module = "androidx.savedstate:savedstate", version.ref = "savedstate" }
androidx-savedstate-ktx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "savedstate" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout-version" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2-version" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "work-runtime-version" }
bcpkix-jdk15on = { module = "com.madgag.spongycastle:bcpkix-jdk15on", version.ref = "bcpkix-jdk15on-version" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
commonmark-java = { module = "com.github.atlassian:commonmark-java", version.ref = "commonmark-java-version" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3-version" }

core = { module = "com.afollestad.material-dialogs:core", version.ref = "core-version" }
crashreport = { module = "com.tencent.bugly:crashreport", version.ref = "crashreport-version" }

expandablerecyclerview = { module = "com.thoughtbot:expandablerecyclerview", version.ref = "expandablerecyclerview-version" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

groovy-json = { module = "org.codehaus.groovy:groovy-json", version.ref = "groovy-json-version" }
keeplive = { module = "com.fanjun:keeplive", version.ref = "keeplive-version" }
licensesdialog = { module = "de.psdev.licensesdialog:licensesdialog", version.ref = "licensesdialog-version" }
log4j = { module = "log4j:log4j", version.ref = "log4jVersion" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4jVersion" }
logbackAndroid = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroidVersion" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "core" }
material-dialogs-commons = { module = "com.afollestad.material-dialogs:commons", version.ref = "commons-version" }

org-eclipse-paho-android-service = { module = "org.eclipse.paho:org.eclipse.paho.android.service", version.ref = "org-eclipse-paho-android-service-version" }
org-eclipse-paho-client-mqttv3 = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "org-eclipse-paho-client-mqttv3-version" }

androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidxPreference" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
#lifecycle
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
android-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
# androidx compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version = "1.7.0-beta07" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material = { module = "androidx.compose.material:material", version = "1.7.0-beta07" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-animation-core = { module = "androidx.compose.animation:animation-core" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
# accompanist
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist-version" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-version" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist-version" }
accompanist-appcompat-theme = { module = "com.google.accompanist:accompanist-appcompat-theme", version.ref = "accompanist-version" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist-version" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-version" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist-version" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-version" }

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }

commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidxWebkit" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidxDocumentfile" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
junit = { module = "junit:junit", version.ref = "junit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

quickie-bundled = { module = "io.github.g00fy2.quickie:quickie-bundled", version.ref = "quickie-bundled-version" }
recyclerview-flexibledivider = { module = "com.yqritc:recyclerview-flexibledivider", version.ref = "recyclerview-flexibledivider-version" }

rootshell = { module = "com.github.Stericson:RootShell", version.ref = "rootshell-version" }
roundedimageview = { module = "com.makeramen:roundedimageview", version.ref = "roundedimageview-version" }

rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxjava2-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid2" }

leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
leakcanary-object-watcher-android = { module = "com.squareup.leakcanary:leakcanary-object-watcher-android", version.ref = "leakcanary" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

andserver-processor = { module = "com.yanzhenjie.andserver:processor", version.ref = "andserver" }
andserver-api = { module = "com.yanzhenjie.andserver:api", version.ref = "andserver" }
andserver = { module = "com.yanzhenjie.andserver:plugin", version.ref = "plugin-version" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }

enhancedfloaty = { module = "com.github.hyb1996:EnhancedFloaty", version.ref = "enhancedfloaty-version" }
android-multi-level-listview = { module = "com.github.hyb1996:android-multi-level-listview", version.ref = "android-multi-level-listview-version" }
mutabletheme = { module = "com.github.hyb1996:MutableTheme", version.ref = "mutabletheme-version" }
settingscompat = { module = "com.github.hyb1996:settingscompat", version.ref = "settingscompat-version" }

speed-dial-compose = { module = "com.leinardi.android:speed-dial.compose", version.ref = "speed-dial-compose-version" }
tbssdk = { module = "com.tencent.tbs:tbssdk", version.ref = "tbssdk-version" }

tesseract4android = { module = "cz.adaptech:tesseract4android", version.ref = "tesseract4android-version" }

text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "mlkitTextRecognition" }
text-recognition-chinese = { module = "com.google.mlkit:text-recognition-chinese", version.ref = "mlkitTextRecognition" }
text-recognition-japanese = { module = "com.google.mlkit:text-recognition-japanese", version.ref = "mlkitTextRecognition" }
text-recognition-devanagari = { module = "com.google.mlkit:text-recognition-devanagari", version.ref = "mlkitTextRecognition" }
text-recognition-korean = { module = "com.google.mlkit:text-recognition-korean", version.ref = "mlkitTextRecognition" }

utils-everywhere = { module = "com.github.SenhLinsh:Utils-Everywhere", version.ref = "utils-everywhere-version" }
websocket2 = { module = "com.dhh:websocket2", version.ref = "websocket2-version" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j-version" }
# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

autojs-android-application = { id = "autojs.android.application", version = "unspecified" }
autojs-android-application-compose = { id = "autojs.android.application.compose", version = "unspecified" }
autojs-android-library = { id = "autojs.android.library", version = "unspecified" }
autojs-jvm-library = { id = "autojs.jvm.library", version = "unspecified" }
[bundles]
ktor = [
    "ktor-server-core",
    "ktor-server-netty",
    "ktor-server-websockets",
    "ktor-client-websockets",
    "ktor-client-okhttp",
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
]
accompanist = [
    "accompanist-webview",
    "accompanist-systemuicontroller",
    "accompanist-insets-ui",
    "accompanist-appcompat-theme",
    "accompanist-swiperefresh",
    "accompanist-pager",
    "accompanist-pager-indicators",
    "accompanist-permissions"
]
