name: Android CI test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "README_en.md"
  pull_request:
    paths-ignore:
      - "README.md"
      - "README_en.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Build Docs
        run: |
          pushd autojs/src/js-api
          npm install
          npm run docs
          popd
          rm -rf docs/v2/docs/nodejs/docs
          mv autojs/src/js-api/docs docs/v2/docs/nodejs/
          pushd docs/v2/
          npm install
          npm run build
          popd
          mkdir -p app/src/main/assets/docs/v2
          mv docs/v2/build/* app/src/main/assets/docs/v2/
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build with Gradle
        run: |
          chmod 777 ./gradlew 
          ./gradlew autojs:buildJsModule
          ./gradlew :inrt:assemble 
          ./gradlew :app:assembleRelease
      - uses: actions/upload-artifact@v3
        with:
          name: apks(no signing)
          path: app/build/outputs/apk/v7/release/*.apk